# Some applications read the EDITOR variable to determine your favourite text
# editor. So uncomment the line below and enter the editor of your choice :-)
#export EDITOR=/usr/bin/vim
#export EDITOR=/usr/bin/mcedit

EMACS=$(which emacs)
VIM=$(which vim)
VI=$(which vi)
if [ -e $EMACS ]; then
   export EDITOR="$EMACS -nw"
   export VISUAL="$EMACS -nw"	
elif [ -e ${VIM} ]; then
    export EDITOR=${VIM}
    export VISUAL=${VIM}
elif [ -e ${VI} ]; then 
    export EDITOR=${VI}
    export VISUAL=${VI}
fi

test -s ~/.alias && . ~/.alias || true
export NO_AT_BRIDGE=1

IGNOREEOF=3



# Save path so, if we re-run ourselves, the path doesn't get needlessly long

if [ "${SAVED_PATH:-==Unset==}" = "==Unset==" ]; then
    export SAVED_PATH="${PATH}"
else
    export PATH="${SAVED_PATH}"
fi

# Some systems have less, some don't - if we don't, just use more

if ( type less > /dev/null 2>&1 ); then
    export LESS="-ImRs"
    export PAGER="less"
else
    alias less="more"
    export MORE="-is"
fi

# For 'ls', use colors if we have them (and use LS_OPTIONS if it exists)

if [ $(uname -s) = "Linux" -a -f /etc/SuSE-release ]; then
    if [ "${LS_OPTIONS}" != "" ]; then
	export LS_OPTIONS="${LS_OPTIONS} -p"
    else
	alias ls="ls -N --color=tty -T 0 -p"
    fi
else
    alias ls="ls -p"
fi

# Generic settings by O/S

for p in /usr/local/bin /opt/bin $HOME/bin $HOME/.cargo/bin; do
    if [ -d $p && echo $PATH | grep -q -v $p ]; then  
	export PATH="$p:$PATH"
    fi
done
    
case `uname -s` in

    Darwin)
	alias ps-scx="ps -ef | grep cim"
	alias users="users | tr ' ' \"\n\" | sort -u | tr \"\n\" ' '; echo"
	;;


    Linux)
	# alias ps-scx="ps aux | egrep \"cim|scx\""
	alias users="users | tr ' ' \"\n\" | sort -u | tr \"\n\" ' '; echo"
	export PATH=$PATH:/usr/sbin

	export PS1="\u:\W> "
	;;


    *)
	;;
esac

